openziti/ziti-console

- projects/ziti-console-lib/src/lib/assets/html/service-router-policies.htm
* Fixed initialization of attribute selectors with proper MultiSelect component setup
> #208 - Router Role Attributes and Service Role Attributes are not populating while creating Service/Router Policies

- projects/ziti-console-lib/src/lib/assets/languages/en-us.json
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.service.ts
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.html
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.ts
- projects/ziti-console-lib/src/lib/features/reset-enrollment/reset-enrollment.component.html
- projects/ziti-console-lib/src/lib/features/reset-enrollment/reset-enrollment.component.ts
- projects/ziti-console-lib/src/lib/features/reset-enrollment/reset-enrollment.service.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
- projects/ziti-console-lib/src/lib/services/node-data.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-controller-data.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-data.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/lib/shared/list-page-component.class.ts
- projects/ziti-console-lib/src/public-api.ts
> Added options to identities page list menu & QR Code component to support "re-issue" action for enrollment tokens

- projects/ziti-console-lib/src/lib/assets/html/cas.htm
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-token/table-cell-token.component.ts
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.html
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.scss
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.html
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.scss
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.component.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
* Added "Click to expand" functionality to QR Code component
* Fixed enrollment token button display on edge router edit form
* Added underline styling for clickable links on the preview-list component
> #235 Make QR code registration expandable for smaller resolutions

- projects/app-ziti-console/src/app/login/login.component.html
- projects/app-ziti-console/src/app/login/login.component.ts
If ZAC is running on a network controller and has available Edge API's then don't show the input fields to specify a controller URL/Name. Instead, just show the Username/Password screen
> Check if ZAC origin is has available Edge API's and only show Username/Password screen if so

- projects/app-ziti-console/src/app/login/login.component.html
- projects/app-ziti-console/src/app/login/login.component.ts
* Prevent overwrite of the selected controller when settings change event is triggered
* Added loading indicator to login screen
> Fixed initialization of login page when running ZAC on ziti controller

- projects/app-ziti-console/src/app/login/controller-login.service.ts
- projects/app-ziti-console/src/app/login/login.component.ts
- projects/app-ziti-console/src/app/login/node-login.service.ts
- projects/ziti-console-lib/src/lib/services/login-service.class.ts
- projects/ziti-console-lib/src/lib/services/noop-login.service.ts
closes #275 
* Moved the `checkOriginForController` function into the login service
* This function should always return`false` when running ZAC via the node server
> #275 The "Select Edge Controller" dropdown is hidden on the login page after logout

- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
Fixes errors:
`error TS2554: Expected 0-2 arguments, but got 3.`
and
`error TS2341: Property 'growlerService' is private and only accessible within class 'ProjectableForm'.`
> Fix issues related to building new simple service form

- projects/ziti-console-lib/src/lib/features/creation-summary-dialog/creation-summary-dialog.component.html
*This option is not functional yet
relates to #285
> Remove "hide this summary" option on summary modal

- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.ts
closes issue #310 - When deleting edge router(s) the delete modal does not populate the names of the edge routers that the user is trying to delete. Currently the modal list shows as empty.
> changed to pull item instead of item id so name will show

- projects/app-ziti-console/src/app/login/controller-login.service.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/forwarding-config/forwarding-config.component.html
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/forwarding-config/forwarding-config.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/port-ranges/port-ranges.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/protocol-address-port/protocol-address-port-input.component.html
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/protocol-address-port/protocol-address-port-input.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.service.ts
- projects/ziti-console-lib/src/lib/services/schema.service.ts
- projects/ziti-console-lib/src/lib/services/validation.service.ts
closes #307 
Will highlight missing/required fields and display a more user friendly error message growler.
See below screenshot for an example:
> Added client-side checks for forwarding configs in advanced services

- projects/app-ziti-console/src/app/app.module.ts
- projects/app-ziti-console/src/app/examples/extension-service/README.md
- projects/app-ziti-console/src/app/examples/extension-service/example-extension.service.ts
- projects/ziti-console-lib/src/lib/features/card-list/card-list.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.html
- projects/ziti-console-lib/src/lib/features/extendable/extensions-noop.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-header/form-header.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-header/form-header.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.html
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
* refactored header component "requestActions()" functions to emit generic actions to support extension service actions
* added No-Op functions for forms that don't require additional "More Actions" items
> Allow ZAC extensions to define additional items for the "More Actions" drop down

- .github/workflows/docker-publish.yml
- .github/workflows/main.yml
- .github/workflows/push-zac-container.yml
- .github/workflows/releases.yml
- CHANGELOG.md
- docker-images/zac/Dockerfile
- docker-images/zac/README.md
- docker-images/ziti-console-assets/Dockerfile
- docker-images/ziti-console-assets/README.md
- pushLatestDocker.sh
This container image is in a transitional state now that the node integration is deprecated in favor of the SPA deployment model. 
This does not change how the node integration behaves in Docker or Kubernetes. Only the SPA build's base URL is updated with this change. This allows the existing SPA build to be used wherever this image is deployed, most notably by the ziti-controller image, e.g. https://github.com/openziti/ziti/blob/605fe4e5c36c7c898894a4a524603897b81e04e8/dist/docker-images/ziti-controller/Dockerfile#L5. 
This image will be refactored once more when the node integration is decommissioned to remove the node integration, preserving only the SPA build.
> add container image for the spa build

- projects/app-ziti-console/src/app/examples/extension-service/example-extension.service.ts
- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.html
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.html
- projects/ziti-console-lib/src/lib/features/extendable/extensions-noop.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.html
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.html
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
* Added "Re-enroll" menu item on routers list page
* Added button to re-enroll on router edit form (if registration is expired)
* Added refresh events to be triggered when router updates are made
*
> Enable "Re-enroll" edge router feature in ZAC

- .github/workflows/mattermost-webhook.yml
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
> Fix editing and saving of configs on the Config Management page

- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
I have removed the code that restricted display/access to the Visualizer menu based on identity typeId.
> show the identity service path visualizer menu for all identities.

- projects/ziti-console-lib/src/lib/assets/scripts/components/multiselect.js
* Removed validation on the "selected" field/parameter when drawing the item html, as this is always a boolean value and not user input
closes #378
> Fix selection of attributes using the multiselect widget

- projects/app-ziti-console/src/app/services/simple-ziti-domain-controller.service.ts
- projects/ziti-console-lib/src/lib/features/wrappers/node-wrapper.service.ts
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-domain-controller.service.ts
* Added new 'handleUnauthorized()' function to ZitiDomainControllerService interface
* Moved response handling to new function `handleServiceResult()` for zac-wrapper.service
closes #376
> Improve handling of error responses from ziti controller

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/src/lib/features/card-list/card-list.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-name/table-cell-name.component.html
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-name/table-cell-name.component.scss
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-name/table-cell-name.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.html
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/lib/shared/list-page-component.class.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- server-edge.js
Angular support the opening of various pages/screens via "deep routes" or "deep linking, so that a specific entity can be loaded via an ID included in the URL path.
This will allow users to go to the url `/identities/some-ziti-id`, and open the identity edit page with the details of a specific identity already loaded on the page.
Also wrapped the "name" cell render with an anchor tag to allow the "open in new tab" behavior via browser context menu.
> Enable the opening of the identity create/edit forms via deep linking

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-name/table-cell-name.component.html
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-name/table-cell-name.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
This will allow users to go to the url /identities/some-ziti-id, and open the identity edit page with the details of a specific identity already loaded on the page.
Also wrapped the "name" cell render with an anchor tag to allow the "open in new tab" behavior via browser context menu.
> Enable the opening of the edge router create/edit forms via deep linking

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/src/lib/features/card-list/card-list.component.html
- projects/ziti-console-lib/src/lib/features/card-list/card-list.component.ts
- projects/ziti-console-lib/src/lib/features/card/card.component.html
- projects/ziti-console-lib/src/lib/features/card/card.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.html
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.html
- projects/ziti-console-lib/src/lib/pages/services/services-page.component.html
- projects/ziti-console-lib/src/lib/pages/services/services-page.component.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.service.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
- projects/ziti-console-lib/src/public-api.ts
- server-edge.js
This will allow users to go to the url `/services/some-ziti-id`, and open the services edit page with the details of a specific identity already loaded on the page.
Also wrapped the "name" cell render, and the service type cards with an anchor tag to allow the "open in new tab" behavior via browser context menu.
> Enable the opening of the services create/edit forms via deep linking

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
- projects/ziti-console-lib/src/lib/pages/configurations/configurations-page.component.html
- projects/ziti-console-lib/src/lib/pages/configurations/configurations-page.component.ts
- projects/ziti-console-lib/src/lib/pages/configurations/configurations-page.service.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.service.ts
This will allow users to go to the url `/configs/some-ziti-id`, and open the configs edit page with the details of a specific identity already loaded on the page.
Also wrapped the "name" cell render, and the service type cards with an anchor tag to allow the "open in new tab" behavior via browser context menu.
> Enable the opening of the configs create/edit forms via deep linking

- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.ts
- projects/ziti-console-lib/src/lib/version.ts
Adding trim function to get rid of whitespace on form names. Closes #424
> adding .trim to get rid of excessive whitespaces on form names - closes #424

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.component.html
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.service.ts
This will allow users to go to the url `/service-policies/some-ziti-id`, and open the service policies edit page with the details of a specific identity already loaded on the page.
Also wrapped the "name" cell render, and the service type cards with an anchor tag to allow the "open in new tab" behavior via browser context menu.
> Enable the opening of the service policies create/edit forms via deep linking

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.service.ts
- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.component.html
- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.service.ts
This will allow users to go to the url `/router-policies/some-ziti-id`, and open the router policies edit page with the details of a specific identity already loaded on the page.
Also wrapped the "name" cell render, and the service type cards with an anchor tag to allow the "open in new tab" behavior via browser context menu.
> Enable the opening of the edge router policies create/edit forms via deep linking

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/app-ziti-console/src/app/app.module.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-edge-router-policy/service-edge-router-policy-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-edge-router-policy/service-edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-edge-router-policy/service-edge-router-policy-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
- projects/ziti-console-lib/src/lib/models/service-edge-router-policy.ts
- projects/ziti-console-lib/src/lib/pages/service-edge-router-policies/service-edge-router-policies-page.component.html
- projects/ziti-console-lib/src/lib/pages/service-edge-router-policies/service-edge-router-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/service-edge-router-policies/service-edge-router-policies-page.service.ts
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
* Added ag-grid implementation of data table
* Added filtering for router & service roles columns
* Added new create/edit form and support for "deep linking" of routes via zitiId
closes #430
> New Service Edge Router Policies List Page and Form

- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/config-editor/config-editor.component.html
- projects/ziti-console-lib/src/lib/features/config-editor/config-editor.component.ts
- projects/ziti-console-lib/src/lib/features/json-view/json-view.component.html
- projects/ziti-console-lib/src/lib/features/json-view/json-view.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
* Added event listeners for key-up and mouse-up events to check for changes to the data model
closes #432
> Persist changes to config when editing in JSON view

- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-name/table-cell-name.component.html
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-name/table-cell-name.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/pages/configurations/configurations-page.service.ts
- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.service.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
- projects/ziti-console-lib/src/lib/pages/service-edge-router-policies/service-edge-router-policies-page.service.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.service.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.service.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
* Added router event listeners to the list-page.class and projectable-form.class to determine what the basePath is of the page/form
* This will allow the deep-linking behavior to work for ZAC when it's hosted at any `baseHref`
closes #436
> Enable "deep link" navigation for dynamic routes

- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-edge-router-policy/service-edge-router-policy-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-data.service.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
> Correctly show associated entities when using the #all attribute

- projects/ziti-console-lib/src/lib/features/visualizer/identity-service-path/identity-service-path.helper.ts
The code fix for the link status issue for a link created between the service and router. 
The fix was tested in a simplified docker-compose network setup:
> fix for router hosted service link status(#487)

- projects/app-ziti-console/src/assets/styles/tables.scss
- projects/ziti-console-lib/src/lib/assets/styles/forms.css
- projects/ziti-console-lib/src/lib/assets/styles/header.css
- projects/ziti-console-lib/src/lib/assets/styles/ziti.css
- projects/ziti-console-lib/src/lib/features/card/card.component.scss
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-menu/table-cell-menu.component.scss
- projects/ziti-console-lib/src/lib/features/data-table/column-headers/table-column-default/table-column-default.component.scss
- projects/ziti-console-lib/src/lib/features/data-table/column-headers/table-column-menu/table-column-menu.component.scss
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.scss
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/object/object.component.scss
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/text-list/text-list-input.component.scss
- projects/ziti-console-lib/src/lib/features/json-view/json-view.component.scss
- projects/ziti-console-lib/src/lib/features/multi-action-button/multi-action-button.component.scss
- projects/ziti-console-lib/src/lib/features/overrides/overrides.component.scss
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-field-container/form-field-container.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-header/form-header.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.scss
- projects/ziti-console-lib/src/lib/features/reset-enrollment/reset-enrollment.component.scss
- projects/ziti-console-lib/src/lib/features/sidebars/side-navbar/side-navbar.component.scss
- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.scss
- projects/ziti-console-lib/src/lib/features/visualizer/network-visualizer/network-visualizer.component.scss
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.scss
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.scss
- projects/ziti-console-lib/src/lib/pages/services/services-page.component.scss
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
> Use CSS variables for input border width & radius

- docker-images/zac/Dockerfile
- docker-images/ziti-console-assets/Dockerfile
- projects/ziti-console-lib/src/lib/.gitignore
- projects/ziti-console-lib/src/lib/version.ts
1. prune and ignore hard-coded lib version.ts file
1. reorder Dockerfile builds to use current version instead of hard-coded version.ts file
> prune and ignore hard-coded lib version.ts file

- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
- projects/ziti-console-lib/src/lib/services/node-data.service.ts
Use the "raw filter" option, which allows filtering of data via columns other than the "name" column, when running ZAC via the node proxy server
closes #550
> Fix filtering of configs based on config type when editing a service

- package-lock.json
- projects/app-ziti-console/src/app/login/controller-login.service.ts
- projects/app-ziti-console/src/app/login/login.component.html
- projects/app-ziti-console/src/app/login/login.component.ts
- projects/app-ziti-console/src/app/login/node-login.service.ts
- projects/app-ziti-console/src/app/services/node-settings.service.ts
- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/selector/selector-input.component.scss
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/selector/selector-input.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/string/string-input.component.scss
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/string/string-input.component.ts
- projects/ziti-console-lib/src/lib/services/schema.service.ts
- projects/ziti-console-lib/src/lib/services/settings-service.class.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- release-notes.md
- server.js
* When users attempt to login to a controller that is not reachable via the hosted ZAC location, show a help text icon indicating what the potential issue may be.
closes #568
> Show login help text when entered controller URL is not reachable

- .github/dependabot.yml
- .github/workflows/docker-publish.yml
- README.md
- build.sh
- docker-images/zac/Dockerfile
- docker-images/ziti-console-assets/Dockerfile
- package-lock.json
- package.json
- projects/ziti-console-lib/README.md
- projects/ziti-console-lib/package.json
- publishSharedLib.sh
This PR asks GitHub to send us PRs to upgrade dependencies with known security vulnerabilities for which a patched version is available.
There are two stages to enable this behavior:
1. this PR
1. in repo settings, enable Dependabot security PRs
> trigger pull requests for vulnerable dependencies

- projects/ziti-console-lib/src/lib/features/config-editor/config-editor.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.service.ts
* Also fixes issue where "undefined" config properties are registering as invalid. Instead we should strip them from the model before validating
> "Create and attach" button label should just say "attach" when adding existing config to a service

- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
* If saved without entering a value in the field, "claims" input should be 'red' with an error
* If anything is entered into claims, the toggle should toggle to "on". If deleted all the content it should toggle to 'off'
> Improve default behavior for JWT Signer "claims" property

- projects/app-ziti-console/src/app/login/controller-login.service.ts
- projects/app-ziti-console/src/app/login/login.component.html
- projects/app-ziti-console/src/app/login/login.component.scss
- projects/app-ziti-console/src/app/login/login.component.ts
- projects/ziti-console-lib/src/lib/services/login-service.class.ts
- server.js
Require available edge controllers to be pre-defined using environment variable `ZAC_CONTROLLER_URLS`
Removed the option to add controller url via the console/node API
closes #625
> Specify a list of pre-defined edge controllers when running the node server

- package.json
- projects/ziti-console-lib/package.json
- release-notes.md
* [Issue #629](https://github.com/openziti/ziti-console/issues/629) - New Config Types List Page and Edit Form
* [Issue #625](https://github.com/openziti/ziti-console/issues/625) - Specify a list of pre-defined edge controllers when running the node server
* [Issue #624](https://github.com/openziti/ziti-console/issues/624) - Remove file upload utility and node service
This release will require all users deploying ZAC via the NodeJS server to specify a pre-defined list of ziti edge controller URL's in order to connect to a controller. To do this, users must define an environment variable called ZAC_CONTROLLER_URLS. It must be a comma seperated list of URLS. For example:
On Mac/Linux:
`export ZAC_CONTROLLER_URLS=https://localhost:1280,https://example.domain.io:443`
On Windows:
`set …
> Release 3.9.0

- .github/workflows/docker-publish.yml
- RELEASE.md
...due to reliability issues with Docker's experimental GHA cache
> use registry cache instead of experimental gha cache method

- projects/ziti-console-lib/src/lib/services/ziti-controller-data.service.ts
closes #418 
Uses the `icontains` filter "verb" by default.
> Make search case-insensitive
