- package.json
- server.cjs
- server.js
- web.config
Move the fixed Zitification to master
> Zitification

- assets/languages/en-us.json
> fix typo in occurreds

- run-zac.sh
- server.js
> wait for files before starting ZAC in docker

- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.html
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
* Updated fields for Identities, and Routers CSV download file
* Fixed display of Registration Token/QR Code Component
> Fixes for Identities, Routers pages

- projects/app-ziti-console/src/styles.scss
- projects/ziti-console-lib/src/lib/assets/styles/dark.css
- projects/ziti-console-lib/src/lib/assets/styles/ziti.css
- projects/ziti-console-lib/src/lib/assets/svgs/Confirm_Trash.svg
- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.html
- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.scss
- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-select/table-cell-select.component.scss
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/checkbox-list/checkbox-list-input.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/checkbox-list/checkbox-list.component.scss
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.component.html
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.component.scss
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.component.ts
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
- projects/ziti-console-lib/src/lib/pages/configurations/configurations-page.component.ts
- projects/ziti-console-lib/src/lib/pages/configurations/configurations-page.service.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.html
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.component.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/lib/shared/list-page-component.class.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
- Update confirmation modal component to take a list of names to display when deleting
- Refactored/consolidated repeated "delete" logic for new list pages into the ListPageComponent and ListPageService classes
> Display items to be deleted in prompt #186

- projects/ziti-console-lib/src/lib/assets/scripts/model/data.js
> #237 Click outside to close table menu

- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.html
- projects/ziti-console-lib/src/lib/shared/list-page-component.class.ts
> #241 QR Code and JWT icons not showing in list table after re-issuing enrollment tokens for identities

- projects/ziti-console-lib/src/lib/assets/html/config-types.htm
- projects/ziti-console-lib/src/lib/assets/scripts/modal.js
- projects/ziti-console-lib/src/lib/assets/scripts/model/data.js
- projects/ziti-console-lib/src/lib/assets/styles/forms.css
- projects/ziti-console-lib/src/lib/assets/styles/ziti.css
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
> #239 Prevent users from deleting system generated config types

- Dockerfile
- package.json
- release-notes.md
* Update release version and notes
* Also remove reference to previously deleted version.txt file
* Fix @angular/cdk version mismatch
> Updates for ziti console release 3.0.6

- package.json
- projects/ziti-console-lib/package.json
Remove unneeded @openziti/ziti-console dependency from root package.json
> Ziti console release 3.0.6

- projects/ziti-console-lib/src/lib/features/projectable-forms/form-header/form-header.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-header/form-header.component.scss
> #258 SAVE button is pushed off the page if entity name has a large number of characters

- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
> #265 - Titles and page text don't display if locale region is anything other than en-us

- projects/ziti-console-lib/src/lib/features/overrides/overrides.component.html
- projects/ziti-console-lib/src/lib/features/overrides/overrides.component.scss
- projects/ziti-console-lib/src/lib/features/overrides/overrides.component.ts
> Fix displayed text when selecting from overrides dropdowns

- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
closes https://github.com/openziti/ziti-console/issues/294
> Add missing component declaration in shared library

- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.service.ts
> Fix adding configs to a service that have empty object properties

- projects/ziti-console-lib/src/lib/services/validation.service.ts
* reworked regex to just check for a `.` char
closes #306
> Support deeper subdomains for Simple service "Accessing Hostname/IP"

- projects/ziti-console-lib/src/lib/app.initializer.ts
> Remove the dependency for initializing the settings service when loading the login page

- server.js
> Fix how the ZAC version is read from package.json

- README.md
> Update README.md to reflect the required version of Angular CLI

- projects/ziti-console-lib/src/lib/assets/html/auth-policies.htm
- projects/ziti-console-lib/src/lib/assets/scripts/modal.js
> Add console guard rails for changing the Default Admin and Default Auth Policy

- server.js
> Fix identity reissue of enrollment token

- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.html
- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.scss
- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.ts
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.service.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
* Fix highlighting/selection of added attributes
* Fix escape character behavior to only close dropdown (if open), not entire modal, on first press of escape button
closes #352
> Fix tag selector rendering and usability issues

- docker-images/zac/Dockerfile
- docker-images/ziti-console-assets/Dockerfile
- package.json
- projects/app-ziti-console/tsconfig.app.json
- projects/ziti-console-lib/src/lib/features/sidebars/side-navbar/side-navbar.component.scss
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
- projects/ziti-console-lib/src/lib/version.ts
- projects/ziti-console-lib/src/public-api.ts
- tsconfig.json
- version.js
> Fix display of ZAC version when running/hosting ziti via the network controller

- projects/app-ziti-console/src/index.html
- projects/ziti-console-lib/src/lib/assets/html/auth-policies.htm
- projects/ziti-console-lib/src/lib/assets/html/deprecated/fabric-links.htm
- projects/ziti-console-lib/src/lib/assets/html/deprecated/fabric-routers.htm
- projects/ziti-console-lib/src/lib/assets/html/deprecated/fabric-services.htm
- projects/ziti-console-lib/src/lib/assets/html/organization.htm
- projects/ziti-console-lib/src/lib/assets/html/recipes.htm
- projects/ziti-console-lib/src/lib/assets/html/servers.htm
- projects/ziti-console-lib/src/lib/assets/scripts/components/column.js
- projects/ziti-console-lib/src/lib/assets/scripts/components/multiselect.js
- projects/ziti-console-lib/src/lib/assets/scripts/components/selector-new.js
- projects/ziti-console-lib/src/lib/assets/scripts/components/spectrum.js
- projects/ziti-console-lib/src/lib/assets/scripts/growler.js
- projects/ziti-console-lib/src/lib/assets/scripts/model/data.js
- projects/ziti-console-lib/src/lib/assets/scripts/model/tags.js
- projects/ziti-console-lib/src/lib/assets/scripts/validation-tools.js
- projects/ziti-console-lib/src/lib/assets/scripts/ziti.js
* Added validation utility
* Apply to legacy components/fields
> Enhance input validation

- projects/app-ziti-console/src/app/login/controller-login.service.ts
> Clear session and redirect to login page if ziti session is expired

- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
> Fix filtering by name on the identities list page

- projects/app-ziti-console/src/styles.scss
- projects/ziti-console-lib/src/lib/features/data-table/column-headers/table-column-default/table-column-default.component.html
- projects/ziti-console-lib/src/lib/features/data-table/column-headers/table-column-default/table-column-default.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/column-headers/table-column-filter/table-column-filter.component.scss
- projects/ziti-console-lib/src/lib/features/data-table/column-headers/table-column-filter/table-column-filter.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/data-table-filter.service.ts
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.html
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.scss
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.ts
- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.html
- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.ts
- projects/ziti-console-lib/src/lib/pages/configurations/configurations-page.service.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.component.html
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-controller-data.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
* Added ag-grid implementation of data table
* Added new tag selector widget for filtering role-based columns
* Refactored "createdAt" format function into list-page-service.class
> Replace Service Policies page with new angular components

- projects/ziti-console-lib/src/lib/features/visualizer/identity-service-path/identity-service-path.component.ts
- projects/ziti-console-lib/src/lib/features/visualizer/identity-service-path/identity-service-path.helper.ts
mahesh identified a negative scenario defect.
1. identity with NO Services.
2. click on clear.
3. select NO SERVICES in a select dropdown.
4. The loading svg is active and the page becomes unresponsive.
Fix: added err handler.
> endpoint visualizer, error handling

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/app-ziti-console/src/app/app.module.ts
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-header/form-header.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-header/form-header.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.service.ts
- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.scss
- projects/ziti-console-lib/src/lib/models/service-policy.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.component.html
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.component.ts
- projects/ziti-console-lib/src/lib/services/node-data.service.ts
- projects/ziti-console-lib/src/lib/services/tab-name.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-controller-data.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-data.service.ts
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
* Added new angular components and services to support creation, preview, and editing of service policies
Closes #390
> New Service Policy Create/Edit Form

- .github/workflows/docker-publish.yml
- CHANGELOG.md
- README.md
- RELEASE.md
- docker-images/ziti-console-assets/Dockerfile
- projects/app-ziti-console/src/app/login/controller-login.service.ts
- projects/app-ziti-console/src/app/login/login.component.html
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
> Cert auth and runtime base href

- .github/workflows/releases.yml
- projects/app-ziti-console/src/app/app-routing.module.ts
- publishSharedLib.sh
> Update github actions to publish to public NPM repo

- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.component.html
- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.service.ts
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
* Added ag-grid implementation of data table
* Added filtering for router & identity roles columns
closes #398
> New Edge Router Policy List Page 

- package.json
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.service.ts
- projects/ziti-console-lib/src/lib/services/node-data.service.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
- server.js
> Fix filtering of Service Policies by attribute

- projects/ziti-console-lib/src/lib/assets/styles/tables.css
- projects/ziti-console-lib/src/lib/assets/styles/ziti.css
- projects/ziti-console-lib/src/lib/features/visualizer/network-visualizer/network-visualizer.component.ts
- projects/ziti-console-lib/src/lib/features/visualizer/network-visualizer/network-visualizer.treenodeprocessor.ts
* Styling cleanup of the dashboard nav item
* Don't redraw the entire graph when a node opens
* open nodes & links from left to right
* Fix the "multiple draws" that happen sometimes because node id's are `undefined`
> Changes to network visualizer

- .github/workflows/docker-publish.yml
- docker-images/ziti-console-assets/README.md
> Update baseHref setting in docker build

- projects/app-ziti-console/src/app/guards/authentication.guard.ts
- projects/app-ziti-console/src/app/interceptors/ziti-api.interceptor.ts
- projects/app-ziti-console/src/app/login/login.component.html
- projects/app-ziti-console/src/app/login/login.component.ts
- projects/ziti-console-lib/src/lib/services/login-service.class.ts
Additional changes:
* Display warning growler indicating the expired session
* Prevent display of the "Select a controller" dropdown
closes #450
> Hide the navigation bar when session expires and routing to login page

- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.html
- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.scss
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
> Prevent overflow of attribute items with long names in tag selector component

- package.json
- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/config-editor/config-editor.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.html
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/data-table.service.ts
- projects/ziti-console-lib/src/lib/features/json-view/json-view.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.html
- release-notes.md
* Also fixes persistence of manually sized columns
closes #457
> Resize data table columns when parent container is resized

- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.component.html
> Include entity type on for the "no items" placeholder text of the policies pages

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/forwarding-config/forwarding-config.service.ts
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.html
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.scss
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-edge-router-policy/service-edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.service.ts
> Allow users to navigate to the config edit page via the "Associated Configs" pod

- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.html
- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.scss
- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/data-table-filter.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.ts
- projects/ziti-console-lib/src/lib/services/ziti-controller-data.service.ts
> Validation for the names on simple service summary screen

- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-edge-router-policy/service-edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.ts
- release-notes.md
> Release ziti-console-lib 0.4.8

- angular.json
- build.sh
- docker-images/ziti-console-assets/Dockerfile
> Reduce application bundle size using production configuration

- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.ts
- projects/ziti-console-lib/src/lib/features/tag-selector/tag-selector.component.scss
closes #477 
Also made adjustments to the styling/layout of the tag-selector widget on this page to resolve to resolve some rendering issues.
> Fix display of identity "role" attributes on simple service form

- projects/ziti-console-lib/src/lib/features/data-table/data-table-filter.service.ts
> Save search filters when navigating between the list page and edit screen

- projects/ziti-console-lib/src/lib/features/custom-tags/custom-tags.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router/edge-router-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-edge-router-policy/service-edge-router-policy-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-edge-router-policy/service-edge-router-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper-service.class.ts
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.component.ts
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
- projects/ziti-console-lib/src/lib/models/config.ts
- projects/ziti-console-lib/src/lib/models/edge-router-policy.ts
- projects/ziti-console-lib/src/lib/models/service-edge-router-policy.ts
- projects/ziti-console-lib/src/lib/models/service-policy.ts
- projects/ziti-console-lib/src/lib/services/settings-service.class.ts
> Add Tag Editor to other entity pages

- projects/ziti-console-lib/src/lib/shared/list-page-component.class.ts
> Fix upper bound of pagination controls on list pages

- projects/app-ziti-console/src/app/app.component.ts
- projects/app-ziti-console/src/app/guards/authentication.guard.ts
- projects/app-ziti-console/src/app/interceptors/ziti-api.interceptor.ts
- projects/app-ziti-console/src/app/login/controller-login.service.ts
- projects/app-ziti-console/src/app/login/login.component.ts
- projects/app-ziti-console/src/app/login/node-login.service.ts
- projects/ziti-console-lib/src/lib/assets/scripts/growler.js
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.component.ts
- projects/ziti-console-lib/src/lib/services/login-service.class.ts
- projects/ziti-console-lib/src/lib/services/node-data.service.ts
- projects/ziti-console-lib/src/lib/services/noop-login.service.ts
- projects/ziti-console-lib/src/lib/services/settings-service.class.ts
- projects/ziti-console-lib/src/lib/services/settings.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-data.service.ts
> Improve ziti session expiration handling

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-field-container/form-field-container.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.ts
- projects/ziti-console-lib/src/lib/models/jwt-signer.ts
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.component.html
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.component.scss
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.component.ts
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.service.ts
- projects/ziti-console-lib/src/lib/services/validation.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
- release-notes.md
> New JWT Signers List Page

- projects/ziti-console-lib/src/lib/features/list-page-features/list-page-header/list-page-header.component.html
- projects/ziti-console-lib/src/lib/features/list-page-features/list-page-header/list-page-header.component.scss
- projects/ziti-console-lib/src/lib/features/list-page-features/list-page-header/list-page-header.component.ts
- projects/ziti-console-lib/src/lib/pages/terminators/terminators-page.component.ts
* Also fixed highlighting of selected sub tab
closes #515
> Show sub-tab navigation options for list page header

- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
> Initialize the config editor in form view

- projects/ziti-console-lib/src/lib/assets/html/api-sessions.htm
- projects/ziti-console-lib/src/lib/assets/html/auth-policies.htm
- projects/ziti-console-lib/src/lib/assets/html/cas.htm
- projects/ziti-console-lib/src/lib/assets/html/config-types.htm
- projects/ziti-console-lib/src/lib/assets/html/jwt-signers.htm
- projects/ziti-console-lib/src/lib/assets/html/posture-checks.htm
- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
- projects/ziti-console-lib/src/lib/pages/auth-policies/auth-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/auth-policies/auth-policies-page.service.ts
- projects/ziti-console-lib/src/lib/pages/configurations/configurations-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.ts
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.component.ts
- projects/ziti-console-lib/src/lib/pages/service-edge-router-policies/service-edge-router-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.component.ts
- projects/ziti-console-lib/src/lib/pages/terminators/terminators-page.component.ts
- projects/ziti-console-lib/src/lib/services/tab-name.service.ts
> Prevent default policy warning from showing when it isn't selected

- projects/ziti-console-lib/src/lib/features/config-editor/config-editor.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-header/form-header.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-header/form-header.component.ts
> Prevent actions on save button when "disable" state is applied

- projects/app-ziti-console/src/app/guards/authentication.guard.ts
- projects/app-ziti-console/src/app/interceptors/ziti-api.interceptor.ts
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.component.html
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.component.scss
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.component.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
closes #539 
* Also removed the "session expired" growlers when a user is redirected to the login page.
> Add ability to download network JWT

- projects/ziti-console-lib/src/lib/features/wrappers/zac-wrapper.service.ts
> Fix download of Certificate Authority JWT

- projects/app-ziti-console/src/styles.scss
- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.html
- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.scss
- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-name/table-cell-name.component.ts
- projects/ziti-console-lib/src/lib/features/messaging/growler.component.scss
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.html
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.scss
- projects/ziti-console-lib/src/lib/features/preview-list/preview-list.component.ts
- projects/ziti-console-lib/src/lib/features/preview-selections/preview-selections.component.html
- projects/ziti-console-lib/src/lib/features/preview-selections/preview-selections.component.scss
- projects/ziti-console-lib/src/lib/features/preview-selections/preview-selections.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-field-container/form-field-container.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-field-container/form-field-container.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/form-field-container/form-field-container.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.service.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.scss
- projects/ziti-console-lib/src/lib/pages/auth-policies/auth-policies-page.service.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.component.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.service.ts
- projects/ziti-console-lib/src/lib/services/settings-service.class.ts
- projects/ziti-console-lib/src/lib/services/settings.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/lib/shared/list-page-component.class.ts
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
* In the delete confirmation dialog, include a checkbox option to include orphaned resources, as well as the ability to preview which entities will be deleted
closes #548
> Optionally delete unused/orphaned entities when deleting a Service

- projects/ziti-console-lib/src/lib/features/data-table/data-table-filter.service.ts
- projects/ziti-console-lib/src/lib/features/data-table/table-filter-bar/filter-bar.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.html
- projects/ziti-console-lib/src/lib/pages/services/services-page.component.html
- projects/ziti-console-lib/src/lib/shared/list-page-component.class.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
> Fix synchronization of pagination controls when applying filters to list pages

- projects/ziti-console-lib/src/lib/pages/auth-policies/auth-policies-page.service.ts
> Fix checking for default auth policy when opening edit page

- projects/ziti-console-lib/src/lib/pages/auth-policies/auth-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/configurations/configurations-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-router-policies/edge-router-policies-page.service.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.component.ts
- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
- projects/ziti-console-lib/src/lib/pages/service-edge-router-policies/service-edge-router-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/service-edge-router-policies/service-edge-router-policies-page.service.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.component.ts
- projects/ziti-console-lib/src/lib/pages/service-policies/service-policies-page.service.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.component.ts
- projects/ziti-console-lib/src/lib/pages/services/services-page.service.ts
- projects/ziti-console-lib/src/lib/shared/list-page-component.class.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
* Refactored and consolidated all "download" list table actions into a shared function in the ListPageService class
closes #558
> Fix unresponsive "Download All" option on list tables

- projects/app-ziti-console/src/app/login/controller-login.service.ts
- projects/app-ziti-console/src/app/login/login.component.html
- projects/app-ziti-console/src/app/login/login.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/selector/selector-input.component.ts
* Catch login error response
* Fix initialization of selected item when list items are set for selector component
closes #560
> Maintain selected edge controller in dropdown if login attempt fails

- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.ts
> Prevent opening of duplicate dialogs when QR code is already expanded

- projects/ziti-console-lib/src/lib/pages/edge-routers/edge-routers-page.service.ts
> Fix pagination on edge routers page

- package-lock.json
- package.json
- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/assets/styles/ziti.css
- projects/ziti-console-lib/src/lib/features/config-editor/config-editor.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/checkbox-list/checkbox-list-input.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/forwarding-config/forwarding-config.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/number/number-input.component.scss
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/number/number-input.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/object/object.component.scss
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/port-ranges/port-ranges.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/protocol-address-port/protocol-address-port-input.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/selector/selector-input.component.scss
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/selector/selector-input.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/string/string-input.component.scss
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/string/string-input.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/text-list/text-list-input.component.ts
- projects/ziti-console-lib/src/lib/features/json-view/json-view.component.ts
- projects/ziti-console-lib/src/lib/features/messaging/growler.component.scss
- projects/ziti-console-lib/src/lib/features/messaging/growler.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- release-notes.md
* Validate a config using the config type schema
* Improve styling of invalid input fields
* Improve error messages that are displayed for invalid config fields
closes #562
> Added schema validation and improved invalid styling to config editor

- projects/ziti-console-lib/src/lib/features/config-editor/config-editor.component.html
- projects/ziti-console-lib/src/lib/features/config-editor/config-editor.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/text-list/text-list-input.component.ts
> Fix race condition when trying to display config data in edit form

- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.ts
> Fix selection behavior for router managed identities

- projects/ziti-console-lib/src/lib/features/visualizer/network-visualizer/network-visualizer.component.ts
- projects/ziti-console-lib/src/lib/features/visualizer/network-visualizer/network-visualizer.helper.ts
NW visualizer:
1) components count. defect fix.(Issue #490)
2) grouping/subgrouping node components.  50 objects per group.
> nw visualizer component count fix, groups, subgroups

- projects/ziti-console-lib/src/lib/features/dynamic-widgets/password/password-input.component.ts
- projects/ziti-console-lib/src/lib/features/dynamic-widgets/string/string-input.component.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
> Remove delay in username & password change events during login

- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.ts
- projects/ziti-console-lib/src/lib/models/jwt-signer.ts
- projects/ziti-console-lib/src/lib/pages/certificate-authorities/certificate-authorities-page.service.ts
> Allow users to set "targetToken" property on JWT Signer

- projects/ziti-console-lib/src/lib/features/projectable-forms/service/simple-service/simple-service.component.html
…ities
* Do server side filtering of identities using entered text in attribute selector
> Hosting Configuration in simple service only shows the first 30 identities

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/config-type/config-type-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/config-type/config-type-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/config-type/config-type-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/config-type/config-type-form.service.ts
- projects/ziti-console-lib/src/lib/models/config-type.ts
- projects/ziti-console-lib/src/lib/pages/config-types/config-types-page.component.html
- projects/ziti-console-lib/src/lib/pages/config-types/config-types-page.component.scss
- projects/ziti-console-lib/src/lib/pages/config-types/config-types-page.component.ts
- projects/ziti-console-lib/src/lib/pages/config-types/config-types-page.service.ts
- projects/ziti-console-lib/src/lib/services/validation.service.ts
- projects/ziti-console-lib/src/lib/shared/list-page-component.class.ts
- projects/ziti-console-lib/src/lib/shared/list-page-service.class.ts
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
> Update Config Types Page With Angular Components

- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/projectable-forms/config-type/config-type-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/config-type/config-type-form.service.ts
- projects/ziti-console-lib/src/lib/pages/config-types/config-types-page.component.html
- projects/ziti-console-lib/src/lib/pages/config-types/config-types-page.component.scss
- release-notes.md
> Update layout of config-types list page to fill the main container

- package-lock.json
- package.json
- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/app-ziti-console/src/app/app.component.ts
- projects/app-ziti-console/src/app/app.module.ts
- projects/app-ziti-console/src/app/interceptors/ziti-api.interceptor.ts
- projects/app-ziti-console/src/app/login/callback.component.ts
- projects/app-ziti-console/src/app/login/controller-login.service.ts
- projects/app-ziti-console/src/app/login/login.component.html
- projects/app-ziti-console/src/app/login/login.component.scss
- projects/app-ziti-console/src/app/login/login.component.ts
- projects/app-ziti-console/src/app/page-not-found/page-not-found.component.html
- projects/app-ziti-console/src/app/page-not-found/page-not-found.component.scss
- projects/app-ziti-console/src/app/page-not-found/page-not-found.component.ts
- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/services/auth.service.ts
- projects/ziti-console-lib/src/lib/services/login-service.class.ts
- projects/ziti-console-lib/src/lib/services/settings-service.class.ts
- projects/ziti-console-lib/src/lib/services/settings.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-controller-data.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-data.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/public-api.ts
> Allow users to do OIDC login via External JWT Signers

- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/projectable-forms/edge-router-policy/edge-router-policy-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-edge-router-policy/service-edge-router-policy-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/transit-router/transit-router-form.component.scss
- release-notes.md
> Make sure the identity auth policy is displayed as selected when form is loaded

- projects/ziti-console-lib/src/lib/features/confirm/confirm.component.html
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/service-policy/service-policy-form.component.html
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.component.ts
> Check if ext-jwt-signer is in use before deleting

- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.html
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.scss
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.component.ts
- projects/ziti-console-lib/src/lib/pages/identities/identities-page.service.ts
- projects/ziti-console-lib/src/lib/services/node-data.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-controller-data.service.ts
- projects/ziti-console-lib/src/lib/services/ziti-data.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- release-notes.md
> Add "Reset MFA" option for identities

- projects/app-ziti-console/src/app/interceptors/ziti-api.interceptor.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/service/service-form.component.ts
> Prevent intercept on requests to OIDC config "well-know" endpoint

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/ziti-console-lib/src/lib/features/data-table/table-filter-bar/filter-bar.component.ts
- projects/ziti-console-lib/src/lib/pages/sessions/sessions-page.component.html
- projects/ziti-console-lib/src/lib/pages/sessions/sessions-page.component.ts
- projects/ziti-console-lib/src/lib/pages/sessions/sessions-page.service.ts
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
Updated Sessions list page with new angular components
> New Sessions Page

- projects/app-ziti-console/src/app/login/login.component.scss
- projects/ziti-console-lib/src/lib/assets/styles/ziti.css
- projects/ziti-console-lib/src/lib/features/config-editor/config-editor.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/auth-policy/auth-policy-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/certificate-authority/certificate-authority-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/certificate-authority/verify-certificate/verify-certificate.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/session/session-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/session/session-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/session/session-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/session/session-form.service.ts
- projects/ziti-console-lib/src/lib/features/qr-code/qr-code.component.scss
- projects/ziti-console-lib/src/lib/features/visualizer/identity-service-path/identity-service-path.component.ts
- projects/ziti-console-lib/src/lib/models/session.ts
- projects/ziti-console-lib/src/lib/pages/sessions/sessions-page.component.html
- projects/ziti-console-lib/src/lib/pages/sessions/sessions-page.component.ts
- projects/ziti-console-lib/src/lib/pages/sessions/sessions-page.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
* Also did some cleanup of the default spinner/loader styling and removed unneeded console logs
> Sessions form component

- .github/workflows/docker-publish.yml
- .github/workflows/linux-publish.yml
stop allowing silent failure when publishing linux packages
> fail workflow if publishing linux packages did not occur

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/app-ziti-console/src/app/login/callback.component.ts
- projects/app-ziti-console/src/app/login/controller-login.service.ts
- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/services/auth.service.ts
- projects/ziti-console-lib/src/lib/services/login-service.class.ts
- projects/ziti-console-lib/src/lib/services/noop-login.service.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
> Added "Test Authentication" feature for External JWT signers

- projects/ziti-console-lib/src/lib/features/projectable-forms/configuration/configuration-form.component.ts
```bash
❯ ziti edge update config '422LPZwhL0qjNW70rc98JB' --name 'kentest-intercept-config' --configTypeId 'g7cIWbcGg' --data '{"portRanges":[{"high":1443,"low":1443}],"addresses":["kubernetes.default.svc"],"protocols":["tcp"]}' --tags-json '{}'
Error: unknown flag: --configTypeId
```
> stop setting --configTypeId flag

- projects/app-ziti-console/src/app/app-routing.module.ts
- projects/app-ziti-console/src/app/app.module.ts
- projects/app-ziti-console/src/app/login/callback.component.ts
- projects/app-ziti-console/src/app/login/login.component.ts
- projects/ziti-console-lib/src/lib/features/json-view/json-view.component.html
- projects/ziti-console-lib/src/lib/features/json-view/json-view.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.scss
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/projectable-form.class.ts
- projects/ziti-console-lib/src/lib/pages/callback/callback.component.ts
- projects/ziti-console-lib/src/lib/services/auth.service.ts
- projects/ziti-console-lib/src/lib/services/login-service.class.ts
- projects/ziti-console-lib/src/lib/shared-assets/styles/global.scss
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
> Added additional error handling cases for External JWT Signer test authentication

- package.json
- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/features/data-table/cells/table-cell-name/table-cell-name.component.ts
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.html
- projects/ziti-console-lib/src/lib/features/data-table/data-table.component.ts
- projects/ziti-console-lib/src/lib/features/no-items/no-items.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/identity/identity-form.component.ts
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.html
- projects/ziti-console-lib/src/lib/features/projectable-forms/jwt-signer/jwt-signer-form.component.ts
- projects/ziti-console-lib/src/lib/models/api-session.ts
- projects/ziti-console-lib/src/lib/pages/api-sessions/api-sessions-page.component.html
- projects/ziti-console-lib/src/lib/pages/api-sessions/api-sessions-page.service.ts
- projects/ziti-console-lib/src/lib/pages/callback/callback.component.ts
- projects/ziti-console-lib/src/lib/pages/jwt-signers/jwt-signers-page.component.html
- projects/ziti-console-lib/src/lib/pages/sessions/sessions-page.component.html
- projects/ziti-console-lib/src/lib/pages/sessions/sessions-page.service.ts
- projects/ziti-console-lib/src/lib/pages/terminators/terminators-page.component.html
- projects/ziti-console-lib/src/lib/pages/terminators/terminators-page.service.ts
- projects/ziti-console-lib/src/lib/services/login-service.class.ts
- projects/ziti-console-lib/src/lib/services/validation.service.ts
- projects/ziti-console-lib/src/public-api.ts
- release-notes.md
* Added columns to the list tables
* Removed sort indicators for columns which don't support sort
* Added id vs name column options for associated entities
> Updates and cleanup for sessions and terminators list pages

- package.json
- projects/ziti-console-lib/package.json
- projects/ziti-console-lib/src/lib/pages/callback/callback.component.ts
- projects/ziti-console-lib/src/lib/ziti-console-lib.module.ts
- projects/ziti-console-lib/src/public-api.ts
- release-notes.md
> Fix broken callback redirect after External JWT Authentication

- projects/ziti-console-lib/src/lib/features/visualizer/identity-service-path/identity-service-path.component.html
- projects/ziti-console-lib/src/lib/features/visualizer/identity-service-path/identity-service-path.component.scss
- projects/ziti-console-lib/src/lib/features/visualizer/identity-service-path/identity-service-path.component.ts
CSS changes related to dark mode enable/disable.
The change has been tested in both ZAC and cloud-ziti.
> Identity Visualizer- dark mode enable, disable changes

- projects/ziti-console-lib/src/lib/assets/html/terminators.htm
fixes terminator to point to services tab
> 704- fixes terminator from identities to services tabs
